version: '3.8'

services:
  # Maple AI Backend
  api:
    build: .
    container_name: maple-api-v2
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://maple:maplepass@db:5432/maple_ai
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-me}
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - TTS_PROVIDER=${TTS_PROVIDER:-edge}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - maple-network

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: maple-db-v2
    environment:
      - POSTGRES_USER=maple
      - POSTGRES_PASSWORD=maplepass
      - POSTGRES_DB=maple_ai
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - maple-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: maple-redis-v2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - maple-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: maple-nginx-v2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./static:/var/www/static
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - maple-network

  # Prometheus (monitoring)
  prometheus:
    image: prom/prometheus:latest
    container_name: maple-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - maple-network

  # Grafana (dashboards)
  grafana:
    image: grafana/grafana:latest
    container_name: maple-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - maple-network

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  maple-network:
    driver: bridge
